[package]
name = "rusto_trainuru"
version = "0.1.0"
authors = ["Agustín Marsero <amarsero@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk"
features = ["v3_16"]